<script>
        var accountId = "<?php echo $this->getConfigData('account_id');?>";
        var transMode = "<?php echo $this->getConfigData('trans_mode');?>";
        var tps = "<?php echo $this->getTps();?>";
        var tpsDef = "<?php echo $this->getTpsDef();?>";
        var firstName = "<?php echo $this->getCustomerData()->getFirstName();?>";
        var lastName = "<?php echo $this->getCustomerData()->getLastName();?>";
        var companyName = "<?php echo $this->getCustomerData()->getCompany();?>";
        var iframeUrl = 'https://secure.bluepay.com/interfaces/shpf?SHPF_FORM_ID=magento2';
</script>
<div id="result"></div>
<input type="hidden" id="storeUrl" value="<?php echo $this->getStoreUrl()?>" />
<div class="payment-method">    
    <div class="payment-method-content">    
    <form class="form" id="form">
    <input type="hidden" id="payment_type" name="payment_type">
    <input type="hidden" id="payment_account_mask" name="payment_account_mask">
    <input type="hidden" id="cc_type" name="cc_type">
    <input type="hidden" id="cc_expire_mm" name="cc_expire_mm">
    <input type="hidden" id="cc_expire_yy" name="cc_expire_yy">
    <input type="hidden" id="rrno" name="rrno">
    <input type="hidden" id="master_id" name="master_id">
    <input type="hidden" id="trans_result" name="trans_result">
    <input type="hidden" id="message" name="message">
    <fieldset data-bind="attr: {class: 'fieldset payment items ccard', id: 'payment_form'}">
    <legend class="legend">
        <span><!-- ko i18n: 'Payment Information'--><!-- /ko --></span>
    </legend><br />
    <!-- /ko -->
    <div class="field type" data-bind="attr: {id: 'bluepay_payment_payment_type_div'}">
            <label for="payment_type">
                <span>Payment Type</span>
            </label>
            <div class="control">
                <div class="fields group group-2">
                    <div class="field no-label month">
                        <div class="control">
                            <select name="payment[payment_type]" id="bluepay_payment_payment_type" style="width: 280px">
                                <option value="CC">Credit Card</option>
                                <option value="ACH">eCheck</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <div class="field date required" data-bind="attr: {id: 'bluepay_payment_stored_acct_div'}">
        <div class="control">
                <label data-bind="attr: {for: 'bluepay_payment_stored_acct'}" class="label">
                    <span>Stored Payment Account</span>
                </label>
                <div class="control">
                <div class="fields group group-2">
                    <div class="field no-label month">
                        <div class="control">
                                <select name="payment[stored_acct]" id="bluepay_payment_stored_acct"
                                        style="width: 280px">
                                        <?php
                                        if (count($this->getStoredAccounts()) == 0) {
                                            ?> <option value="">-No payment accounts found-</option> <?php
                                        } else { ?> <option value="">Add a new stored payment account</option> <?php
                                            foreach($this->getStoredAccounts() as $acct) { ?>
                                                <option value="<?= $acct['value'] ?>"><?= $acct['text'] ?></option>
                                            <?php
                                            }
                                        } ?>
                                </select>
                                <button class="action primary checkout" id="deleteBtn" type="button">
                                    <span>Delete</span>
                                </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <iframe id="iframe" frameBorder="0"></iframe>
    <br/>
    <div class="actions-toolbar">
            <div class="primary">
                <button class="action primary checkout" id="submitBtn" onclick="return submitIframe();"
                        type="submit">
                    <span>Submit</span>
                </button>
            </div>
    </div>

    </fieldset>
    </form>
    </div>
</div>
